//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bquiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bq_Part
    {
        public bq_Part()
        {
            this.bq_QuestionGroup = new HashSet<bq_QuestionGroup>();
        }
    
        public System.Guid PartId { get; set; }
        public System.Guid QuizId { get; set; }
        public string Name { get; set; }
        public byte Order { get; set; }
    
        public virtual bq_Quiz bq_Quiz { get; set; }
        public virtual ICollection<bq_QuestionGroup> bq_QuestionGroup { get; set; }
    }
}
