//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bquiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bq_QuestionGroup
    {
        public bq_QuestionGroup()
        {
            this.bq_Question = new HashSet<bq_Question>();
        }
    
        public System.Guid QuestionGroupId { get; set; }
        public System.Guid QuizId { get; set; }
        public System.Guid PartId { get; set; }
        public string Name { get; set; }
        public byte Order { get; set; }
        public string Paragraph { get; set; }
        public string MediaPath { get; set; }
    
        public virtual bq_Part bq_Part { get; set; }
        public virtual ICollection<bq_Question> bq_Question { get; set; }
        public virtual bq_Quiz bq_Quiz { get; set; }
    }
}
