//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bquiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bq_Test
    {
        public bq_Test()
        {
            this.qb_Answer = new HashSet<qb_Answer>();
        }
    
        public System.Guid TestId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public System.Guid QuizId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual bq_Quiz bq_Quiz { get; set; }
        public virtual ICollection<qb_Answer> qb_Answer { get; set; }
    }
}
